"""empty message

Revision ID: 879b925e3bb8
Revises: d52451c82b28
Create Date: 2024-01-04 12:28:12.566296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '879b925e3bb8'
down_revision = 'd52451c82b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.drop_constraint('hoat_chat_ibfk_1', type_='foreignkey')
        batch_op.drop_column('ham_luong_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ham_luong_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('hoat_chat_ibfk_1', 'ham_luong', ['ham_luong_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
