"""empty message

Revision ID: b630daebc0b8
Revises: 0dcd5c308250
Create Date: 2024-01-04 11:24:26.503998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b630daebc0b8'
down_revision = '0dcd5c308250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nha_cung_cap_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nha_cung_cap', ['nha_cung_cap_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nha_cung_cap_id')

    # ### end Alembic commands ###
