"""empty message

Revision ID: d52451c82b28
Revises: b630daebc0b8
Create Date: 2024-01-04 12:21:43.288762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52451c82b28'
down_revision = 'b630daebc0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sdk', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('solo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('han_su_dung', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hoat_chat', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_thuoc_hoat_chat'), ['hoat_chat'], unique=False)
        batch_op.create_index(batch_op.f('ix_thuoc_note'), ['note'], unique=False)
        batch_op.create_index(batch_op.f('ix_thuoc_sdk'), ['sdk'], unique=False)
        batch_op.create_index(batch_op.f('ix_thuoc_solo'), ['solo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thuoc_solo'))
        batch_op.drop_index(batch_op.f('ix_thuoc_sdk'))
        batch_op.drop_index(batch_op.f('ix_thuoc_note'))
        batch_op.drop_index(batch_op.f('ix_thuoc_hoat_chat'))
        batch_op.drop_column('hoat_chat')
        batch_op.drop_column('note')
        batch_op.drop_column('han_su_dung')
        batch_op.drop_column('solo')
        batch_op.drop_column('sdk')

    # ### end Alembic commands ###
